Remove call to non-existent `function_name` function
- this was a mistake from commit 7987e54c2ec63e1258bcf2ccf1c96c162df3c144
  - this function call should not have been added at all here
- adresses the following `mypy` error:
test_project_python_tests/__init__.py:9: error: Name "function_name" is not defined  [name-defined]