Fix `package__init__files` type hinting to expect a `TextIO`
- adresses the following `mypy` error:
test_project_python/package_builder.py:128: error: "str" has no attribute "write"  [attr-defined]