Fix `package__init__files` type hinting to expect a `List` of `Tuple`s
- adresses the following `mypy` errors:
test_project_python/package_builder.py:132: error: "Collection[Tuple[TextIO, str]]" has no attribute "append"  [attr-defined]
test_project_python/package_builder.py:134: error: "Collection[Tuple[TextIO, str]]" has no attribute "pop"  [attr-defined]