Fix `function_data` type hinting to expect a `Collection` of `Tuple`s
- adresses the following `mypy` errors:
test_project_python_tests/test_package_builder.py:24: error: "object" object is not iterable  [misc]
test_project_python_tests/test_package_builder.py:25: error: Cannot determine type of "input_arguments"  [has-type]
test_project_python_tests/test_package_builder.py:26: error: Cannot determine type of "expected_result"  [has-type]
test_project_python_tests/test_package_builder.py:30: error: Cannot determine type of "input_arguments"  [has-type]
test_project_python_tests/test_package_builder.py:30: error: Cannot determine type of "description"  [has-type]
test_project_python_tests/test_package_builder.py:30: error: Cannot determine type of "expected_result"  [has-type]