Explicitly specify `data_verify_instance_is_from_type` variable type hinting
- adresses the following `mypy` error:
/path/to/test_project/python/test_project_python_tests/test_package_builder.py: note: In function "main":
/path/t0/test_project/python/test_project_python_tests/test_package_builder.py:16:19:16:51: error: Argument 1
to "test_function" has incompatible type "List[object]"; expected
"Tuple[Callable[..., Any], Collection[Tuple[Tuple[Any, ...], str, <nothing>]]]"  [arg-type]
        test_function(data_verify_instance_is_from_type)
                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
- **note** that adding this type hint **also** requires updating the
  `data_verify_instance_is_from_type` to a `tuple` literal from its
  original `list` type since specifying the type of each element of a
  `list` is not possible (but specifying the type of each element of a
  `tuple` **is** possible)
- **note** that using `TypeVar` for variable type hinting
  outside a function is not possible, and trying to do so
  by doing something such as the following

```
data_verify_instance_is_from_type: Tuple[Callable[..., Any], Collection[Tuple[InputArguments, Description, ExpectedResult]]]
```

  will result in the following `mypy` errors:
/path/to/test_project/python/test_project_python_tests/test_package_builder.py:78:108:78:108: error: Type variable
"test_project_python_tests.test_package_builder.ExpectedResult" is unbound  [valid-type]
   ..._verify_instance_is_from_type: Tuple[Callable[..., Any], Collection[Tuple[InputArguments, Description, ExpectedResult]]] = [
                                                                                                             ^
/path/to/test_project/python/test_project_python_tests/test_package_builder.py:78:108:78:108: note: (Hint: Use "Generic[ExpectedResult]" or
"Protocol[ExpectedResult]" base class to bind "ExpectedResult" inside a class)
/path/to/test_project/python/test_project_python_tests/test_package_builder.py:78:108:78:108: note: (Hint: Use "ExpectedResult" in
function signature to bind "ExpectedResult" inside a function)
/path/to/test_project/python/test_project_python_tests/test_package_builder.py:78:128:92:1: error: Incompatible types
in assignment (expression has type "List[object]", variable has type
"Tuple[Callable[..., Any], Collection[Tuple[Tuple[Any, ...], str, ExpectedResult?]]]")  [assignment]
    ..._verify_instance_is_from_type: Tuple[Callable[..., Any], Collection[Tuple[InputArguments, Description, ExpectedResult]]] = [
                                                                                                                                  ^
- this means avoiding all errors requires using a `tuple` literal syntax
  such as the following

```
data_verify_instance_is_from_type: Tuple[Callable[..., Any], Collection[Tuple[Tuple[Any, ...], str, Any]]] = (
                                                                                                             ^ no explicit type cast
```

- **note** that using the `tuple` literal syntax is **critical**,  since
  attempting to do an explicit type cast of the list comprehension into
  a `tuple` **after** building the `list` by doing something such as

```
data_verify_instance_is_from_type: Tuple[Callable[..., Any], Collection[Tuple[Tuple[Any, ...], str, Any]]] = tuple([
                                                                                                             ^ explicit type cast
```

  results in the following `mypy` error:
/path/to/test_project/python/test_project_python_tests/test_package_builder.py:78:110:91:2: error: Incompatible types
in assignment (expression has type "Tuple[object, ...]", variable has type
"Tuple[Callable[..., Any], Collection[Tuple[Tuple[Any, ...], str, Any]]]")  [assignment]
    data_verify_instance_is_from_type: Tuple[Callable[..., Any], Collection[Tuple[Tuple[Any, ...], str, Any]]] = tuple([
                                                                                                                 ^