Fix `InputArguments` type hinting to expect a `Tuple`
- adresses the following `mypy` error:
test_project_python_tests/test_package_builder.py:39: error: List or tuple expected as variadic arguments  [misc]