Fix `acceptable_types` type hinting to expect a `Type` or a `Tuple`
- adresses the following `mypy` error:
test_project_python/package_builder.py:71: error: Argument 2 to "isinstance" has incompatible type "Union[T, Tuple[Any, ...]]"; expected "_ClassInfo"  [arg-type]